#define MAX_LIGHTS 8 * 8 * 8
#define MAX_LIGHTS_PER_CLUSTER 7

// CHECK
#define CLUSTER_X 16
#define CLUSTER_Y 9
#define CLUSTER_Z 24

#define CLUSTER_X_PIXEL_SIZE 80 // 1280/16
#define CLUSTER_Y_PIXEL_SIZE 80 // 720/9

#define NUM_CLUSTERS CLUSTER_X * CLUSTER_Y * CLUSTER_Z
